export type DirectReportPayloadV163 = {
  start_date: string
  end_date: string
  financial: {
    billed_revenue_cents: number
    collections_cents: number
    receivables_cents: number
    operating_expenses_cents: number
    net_operating_result_cents: number
  }
  operations: {
    appointments: number
    completed_visits: number
    cancellations: number
    no_shows: number
    no_show_rate: number
    patients_seen: number
    new_patients: number
  }
  inventory: {
    active_items: number
    low_stock: number
    out_of_stock: number
    expiring_soon: number
    valuation_cents: number
    consumed_quantity: number
  }
  provider_performance?: Array<{
    provider_name: string
    appointments: number
    completed_visits: number
    patients_seen: number
    treatments: number
    no_shows: number
    billed_treatments_cents: number
  }>
  service_demand: Array<{ service_name: string; demand: number; completed: number }>
  top_treatments: Array<{ name: string; performed: number; billed_cents: number }>
}

type Input = {
  report: DirectReportPayloadV163
  scopeName: string
  generatedBy?: string
}

const encoder = new TextEncoder()

function pdfEscape(value: string) {
  return value.replaceAll('\\', '\\\\').replaceAll('(', '\\(').replaceAll(')', '\\)')
}

function php(cents = 0) {
  return `PHP ${(Number(cents || 0) / 100).toLocaleString('en-PH', { minimumFractionDigits: 2, maximumFractionDigits: 2 })}`
}

function safe(value: unknown) {
  return String(value ?? '').replace(/[^\x20-\x7E]/g, '-')
}

function wrap(value: string, width = 78) {
  const words = safe(value).split(/\s+/).filter(Boolean)
  const lines: string[] = []
  let current = ''
  for (const word of words) {
    const next = current ? `${current} ${word}` : word
    if (next.length > width && current) {
      lines.push(current)
      current = word
    } else current = next
  }
  if (current) lines.push(current)
  return lines.length ? lines : ['']
}

function text(x: number, y: number, size: number, value: string, bold = false, rgb = '0.10 0.14 0.21') {
  return `${rgb} rg BT /${bold ? 'F2' : 'F1'} ${size} Tf ${x} ${y} Td (${pdfEscape(safe(value))}) Tj ET\n`
}

function line(x1: number, y1: number, x2: number, y2: number, rgb = '0.86 0.89 0.94', width = 0.7) {
  return `${rgb} RG ${width} w ${x1} ${y1} m ${x2} ${y2} l S\n`
}

function buildPage(input: Input, pageNumber: number, totalPages: number, section: 'summary' | 'operations') {
  const { report, scopeName, generatedBy } = input
  let y = 794
  let body = ''
  body += text(48, y, 17, 'Plamenco Dental Co.', true, '0.10 0.31 0.78'); y -= 22
  body += text(48, y, 10, 'Management Report', true); y -= 18
  body += text(48, y, 9, `Scope: ${scopeName}`); y -= 14
  body += text(48, y, 9, `Reporting period: ${report.start_date} to ${report.end_date}`); y -= 14
  body += text(48, y, 8, `Generated by: ${generatedBy || 'Authorized clinic user'}`, false, '0.36 0.42 0.52'); y -= 18
  body += line(48, y, 547, y, '0.16 0.39 0.88', 1.2); y -= 24

  const sectionTitle = (title: string) => {
    body += text(48, y, 11, title.toUpperCase(), true, '0.16 0.39 0.88')
    y -= 14
    body += line(48, y, 547, y)
    y -= 18
  }
  const row = (label: string, value: string, note?: string) => {
    body += text(56, y, 9, label, true)
    body += text(255, y, 9, value, true, '0.08 0.16 0.30')
    if (note) body += text(360, y, 7.5, note, false, '0.40 0.46 0.56')
    y -= 19
  }

  if (section === 'summary') {
    sectionTitle('Executive summary')
    row('Billed revenue', php(report.financial.billed_revenue_cents), 'Non-void invoices')
    row('Collections', php(report.financial.collections_cents), 'Completed payments')
    row('Receivables', php(report.financial.receivables_cents), 'Outstanding balances')
    row('Operating expenses', php(report.financial.operating_expenses_cents), 'Recorded expenses')
    row('Net operating result', php(report.financial.net_operating_result_cents), 'Billed less expenses')
    y -= 10

    sectionTitle('Clinic operations')
    row('Appointments', String(report.operations.appointments))
    row('Completed visits', String(report.operations.completed_visits))
    row('Cancellations', String(report.operations.cancellations))
    row('No-shows', String(report.operations.no_shows))
    row('No-show rate', `${(report.operations.no_show_rate * 100).toFixed(1)}%`)
    row('Patients seen', String(report.operations.patients_seen))
    row('New patients', String(report.operations.new_patients))
    y -= 10

    sectionTitle('Inventory position')
    row('Active stock items', String(report.inventory.active_items))
    row('Low stock', String(report.inventory.low_stock))
    row('Out of stock', String(report.inventory.out_of_stock))
    row('Expiring soon', String(report.inventory.expiring_soon))
    row('Inventory valuation', php(report.inventory.valuation_cents))
    row('Consumed quantity', Number(report.inventory.consumed_quantity || 0).toLocaleString('en-PH'))
  } else {
    sectionTitle('Service demand')
    const serviceRows = report.service_demand.slice(0, 12)
    if (!serviceRows.length) row('No service activity', '-', 'No records in selected period')
    serviceRows.forEach((item) => row(item.service_name, `${item.demand} requests`, `${item.completed} completed`))
    y -= 10

    sectionTitle('Completed treatments')
    const treatmentRows = report.top_treatments.slice(0, 12)
    if (!treatmentRows.length) row('No completed treatments', '-', 'No records in selected period')
    treatmentRows.forEach((item) => row(item.name, `${item.performed} performed`, php(item.billed_cents)))
    y -= 10

    if (report.provider_performance?.length) {
      sectionTitle('Dentist operations')
      report.provider_performance.slice(0, 10).forEach((item) => {
        const note = `${item.completed_visits} completed, ${item.patients_seen} patients, ${item.no_shows} no-shows`
        row(item.provider_name, php(item.billed_treatments_cents), note)
      })
    }

    y -= 10
    sectionTitle('Report notes')
    const notes = [
      'This report is generated from persisted clinic records for the selected branch and date range.',
      'Financial figures are management reporting values and should be reconciled with the clinic accountant or bookkeeper.',
      'Net operating result is billed revenue less recorded operating expenses; it is not presented as audited net profit.',
    ]
    for (const note of notes) {
      for (const wrapped of wrap(note, 88)) {
        body += text(56, y, 8, wrapped, false, '0.36 0.42 0.52')
        y -= 13
      }
      y -= 4
    }
  }

  body += line(48, 45, 547, 45)
  body += text(48, 30, 7.5, 'Internal management report - Plamenco Dental Co.', false, '0.45 0.50 0.58')
  body += text(486, 30, 7.5, `Page ${pageNumber} of ${totalPages}`, false, '0.45 0.50 0.58')
  return body
}

function pdfObject(id: number, body: string) {
  return `${id} 0 obj\n${body}\nendobj\n`
}

export function buildLiveReportPdfV163(input: Input) {
  const pages = [buildPage(input, 1, 2, 'summary'), buildPage(input, 2, 2, 'operations')]
  const objects: string[] = []
  objects[1] = pdfObject(1, '<< /Type /Catalog /Pages 2 0 R >>')
  objects[2] = pdfObject(2, '<< /Type /Pages /Kids [5 0 R 7 0 R] /Count 2 >>')
  objects[3] = pdfObject(3, '<< /Type /Font /Subtype /Type1 /BaseFont /Helvetica >>')
  objects[4] = pdfObject(4, '<< /Type /Font /Subtype /Type1 /BaseFont /Helvetica-Bold >>')
  objects[5] = pdfObject(5, '<< /Type /Page /Parent 2 0 R /MediaBox [0 0 595 842] /Resources << /Font << /F1 3 0 R /F2 4 0 R >> >> /Contents 6 0 R >>')
  objects[6] = pdfObject(6, `<< /Length ${encoder.encode(pages[0]).length} >>\nstream\n${pages[0]}endstream`)
  objects[7] = pdfObject(7, '<< /Type /Page /Parent 2 0 R /MediaBox [0 0 595 842] /Resources << /Font << /F1 3 0 R /F2 4 0 R >> >> /Contents 8 0 R >>')
  objects[8] = pdfObject(8, `<< /Length ${encoder.encode(pages[1]).length} >>\nstream\n${pages[1]}endstream`)

  let pdf = '%PDF-1.4\n%\xE2\xE3\xCF\xD3\n'
  const offsets = new Array<number>(9).fill(0)
  for (let id = 1; id <= 8; id += 1) {
    offsets[id] = encoder.encode(pdf).length
    pdf += objects[id]
  }
  const xrefOffset = encoder.encode(pdf).length
  pdf += 'xref\n0 9\n0000000000 65535 f \n'
  for (let id = 1; id <= 8; id += 1) pdf += `${String(offsets[id]).padStart(10, '0')} 00000 n \n`
  pdf += `trailer\n<< /Size 9 /Root 1 0 R >>\nstartxref\n${xrefOffset}\n%%EOF`
  return encoder.encode(pdf)
}

export function reportPdfFilenameV163(input: Input) {
  const scope = input.scopeName.toLowerCase().replace(/[^a-z0-9]+/g, '-').replace(/^-|-$/g, '') || 'clinic'
  return `plamenco-report-${scope}-${input.report.start_date}-to-${input.report.end_date}.pdf`
}
