import { StrictMode } from 'react'
import { createRoot } from 'react-dom/client'
import './index.css'
import './styles/billing.css'
import './styles/treatments.css'
import './styles/release-polish.css'
import './styles/modal-fixes.css'
import './styles/payment-recorder.css'
import './styles/inventory-actions.css'
import './styles/expense-actions.css'
import './styles/forms-consent-actions.css'
import './styles/design-system-47a.css'
import './styles/design-system-components-47a.css'
import './styles/auth-47c.css'
import './styles/patient-portal-47d.css'
import './styles/staff-portal-47e.css'
import './styles/dentist-portal-47f.css'
import './styles/admin-portal-47g.css'
import './styles/super-admin-portal-47h.css'
import './styles/final-polish-47i.css'
import './styles/corrective-redesign-48a.css'
import './styles/internal-navigation-white-blue.css'
import './styles/internal-page-foundation-v6.css'
import './styles/internal-clinical-workspaces-v6.css'
import './styles/internal-finance-workspaces-v6.css'
import './styles/internal-operations-workspaces-v6.css'
import './styles/internal-admin-workspaces-v6.css'
import './styles/internal-admin-workspaces-v6-refinements.css'
import './styles/internal-governance-workspaces-v6-refinements.css'
import './styles/settings-workspace-v6.css'
import './styles/super-admin-dashboard-v7.css'
import './styles/super-admin-appointments-v8.css'
import './styles/super-admin-patients-v9.css'
import './styles/super-admin-patients-v10.css'
import './styles/super-admin-dental-records-v11.css'
import './styles/super-admin-treatments-v12.css'
import './styles/super-admin-treatment-plans-v13.css'
import './styles/super-admin-billing-v14.css'
import App from './App.tsx'
import { registerPatientPortalPwa } from './features/patientPortal/pwaRegistration'

registerPatientPortalPwa()

createRoot(document.getElementById('root')!).render(
  <StrictMode>
    <App />
  </StrictMode>,
)
